package_rename_config:
  android:
    app_name: KIWOO # (String) The display name of the android app
    package_name: com.visionmis.kiwoo # (String) The package name of the android app
    # override_old_package: KIWOO # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    # lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: KIWOO # (String) The display name of the ios app
    bundle_name: Kiwoo # (String) The bundle name of the ios app
    package_name: com.visionmis.kiwoo # (String) The product bundle identifier of the ios app
